### ISSUE TITLE
I followed the steps in the readme to run the code with an error

### ISSUE THREAD

**Issue by LeeKoTo** [5tmFPUPx/FSIBP#1]
I followed the steps in the readme to run the code with an error
`
Traceback (most recent call last):
  File "train.py", line 352, in <module>
  File "train.py", line 286, in train_model
    optimal_k = descritpion_cossim(train_description_list, test_description_list, sentence_embedding_model_name)
  File "D:\Download\ProDecoder-master\FSIBP\model_train_eval_code\description_embedding.py", line 32, in descritpion_cossim
    train_cosine_similarities = cosine_similarity(train_description_embeddings)
  File "E:\python3.7\lib\site-packages\sklearn\metrics\pairwise.py", line 1251, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "E:\python3.7\lib\site-packages\sklearn\metrics\pairwise.py", line 153, in check_pairwise_arrays
    estimator=estimator,
  File "E:\python3.7\lib\site-packages\sklearn\utils\validation.py", line 773, in check_array
    "if it contains a single sample.".format(array)
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

`

**Comment by Jtice-moz** [comment]
+1，Has your problem been solved?

**Comment by LeeKoTo** [comment]
@Jtice-moz My problem hasn't been solved yet

**Comment by Jtice-moz** [comment]
@LeeKoTo I solved the problem. BeautifulSoup had an issue parsing the webpage, causing the contents of the description and field name description folders to be empty. 
My solution is to add a header to the file 'Wireshark_field_crawler. py'
`import re 
pattern = r'<td>(.*?)</td>'`
Then modify the field_crawler() function
`def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir):
    for protocol_name in protocol_names_list:
        url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html'
        print(url)
        response = requests.get(url)
        html_content = response.content
        soup = BeautifulSoup(html_content, 'html.parser')
        table = soup.find('table')
        field_name_list = []
        description_list = []
        for row in table.findAll('tr'):
            columns = row.findAll('td')
            if columns:
                cleaned_content = re.sub(r'<wbr/>', '', str(columns[0]))
                field_name = re.search(pattern, cleaned_content, re.DOTALL)
                description = re.search(pattern, str(columns[1]), re.DOTALL)
                field_name_list.append(field_name.group(1))
                description_list.append(description.group(1))
        csv_file_name = str(protocol_name) + '_field_name_description.csv'
        csv_rows = zip(field_name_list, description_list)

        with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)
        
        description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions
        csv_file_name = str(protocol_name) + '_description.csv'
        csv_rows = zip(description_without_duplicate_list)
        with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)`
But I'm not sure if this change is in line with the author's intention.

**Comment by Jtice-moz** [comment]
@LeeKoTo 
I solved the problem. BeautfulSoup made an error parsing the webpage, causing the CSV files in the description and field name description folders to be empty
Firstly, add the following to Wireshark_field_crawler.py
`import re 
pattern = r'<td>(.*?)</td>'`
Then change the field_crawler()
`def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir):
    for protocol_name in protocol_names_list:
        url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html'
        print(url)
        response = requests.get(url)
        html_content = response.content
        soup = BeautifulSoup(html_content, 'html.parser')
        table = soup.find('table')
        field_name_list = []
        description_list = []
        for row in table.findAll('tr'):
            columns = row.findAll('td')
            if columns:
                cleaned_content = re.sub(r'<wbr/>', '', str(columns[0]))
                field_name = re.search(pattern, cleaned_content, re.DOTALL)
                description = re.search(pattern, str(columns[1]), re.DOTALL)
                field_name_list.append(field_name.group(1))
                description_list.append(description.group(1))
        csv_file_name = str(protocol_name) + '_field_name_description.csv'
        csv_rows = zip(field_name_list, description_list)

        with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)
        
        description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions
        csv_file_name = str(protocol_name) + '_description.csv'
        csv_rows = zip(description_without_duplicate_list)
        with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)`
But I'm not sure if this change is in line with the author's intention

**Comment by Jtice-moz** [comment]
@LeeKoTo 
I solved the problem. BeautfulSoup made an error parsing the webpage, causing the CSV files in the description and field name description folders to be empty
Firstly, add the following to Wireshark_field_crawler.py
`import re 
pattern = r'<td>(.*?)</td>'`
Then change the field_crawler()
`def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir):
    for protocol_name in protocol_names_list:
        url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html'
        print(url)
        response = requests.get(url)
        html_content = response.content
        soup = BeautifulSoup(html_content, 'html.parser')
        table = soup.find('table')
        field_name_list = []
        description_list = []
        for row in table.findAll('tr'):
            columns = row.findAll('td')
            if columns:
                cleaned_content = re.sub(r'<wbr/>', '', str(columns[0]))
                field_name = re.search(pattern, cleaned_content, re.DOTALL)
                description = re.search(pattern, str(columns[1]), re.DOTALL)
                field_name_list.append(field_name.group(1))
                description_list.append(description.group(1))
        csv_file_name = str(protocol_name) + '_field_name_description.csv'
        csv_rows = zip(field_name_list, description_list)
        with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)
        description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions
        csv_file_name = str(protocol_name) + '_description.csv'
        csv_rows = zip(description_without_duplicate_list)
        with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_rows:
                writer.writerow(row)`
But I'm not sure if this change is in line with the author's intention

**Comment by Jtice-moz** [comment]
@LeeKoTo  
I solved the problem. BeautfulSoup made an error parsing the webpage, causing the CSV files in the description and field name description folders to be empty 
Firstly, add the following to Wireshark_field_crawler.py 
import re  
pattern = r'<td>(.*?)</td>
Then change the field_crawler() 
def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir): 
    for protocol_name in protocol_names_list: 
        url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html' 
        print(url) 
        response = requests.get(url) 
        html_content = response.content 
        soup = BeautifulSoup(html_content, 'html.parser') 
        table = soup.find('table') 
        field_name_list = [] 
        description_list = [] 
        for row in table.findAll('tr'): 
            columns = row.findAll('td') 
            if columns: 
                cleaned_content = re.sub(r'<wbr/>', '', str(columns[0])) 
                field_name = re.search(pattern, cleaned_content, re.DOTALL) 
                description = re.search(pattern, str(columns[1]), re.DOTALL) 
                field_name_list.append(field_name.group(1)) 
                description_list.append(description.group(1)) 
        csv_file_name = str(protocol_name) + '_field_name_description.csv' 
        csv_rows = zip(field_name_list, description_list) 
﻿ 
        with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file: 
            writer = csv.writer(file) 
            for row in csv_rows: 
                writer.writerow(row) 
         
        description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions 
        csv_file_name = str(protocol_name) + '_description.csv' 
        csv_rows = zip(description_without_duplicate_list) 
        with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file: 
            writer = csv.writer(file) 
            for row in csv_rows: 
                writer.writerow(row)
But I'm not sure if this change is in line with the author's intention

**Comment by Jtice-moz** [comment]
@LeeKoTo  
I solved the problem. BeautfulSoup made an error parsing the webpage, causing the CSV files in the description and field name description folders to be empty 
Firstly, add the following to Wireshark_field_crawler.py 
```
import re  
pattern = r'<td>(.*?)</td>
```
Then change the field_crawler() 
```
def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir): 
    for protocol_name in protocol_names_list: 
        url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html' 
        print(url) 
        response = requests.get(url) 
        html_content = response.content 
        soup = BeautifulSoup(html_content, 'html.parser') 
        table = soup.find('table') 
        field_name_list = [] 
        description_list = [] 
        for row in table.findAll('tr'): 
            columns = row.findAll('td') 
            if columns: 
                cleaned_content = re.sub(r'<wbr/>', '', str(columns[0])) 
                field_name = re.search(pattern, cleaned_content, re.DOTALL) 
                description = re.search(pattern, str(columns[1]), re.DOTALL) 
                field_name_list.append(field_name.group(1)) 
                description_list.append(description.group(1)) 
        csv_file_name = str(protocol_name) + '_field_name_description.csv' 
        csv_rows = zip(field_name_list, description_list) 
        with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file: 
            writer = csv.writer(file) 
            for row in csv_rows: 
                writer.writerow(row) 
        description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions 
        csv_file_name = str(protocol_name) + '_description.csv' 
        csv_rows = zip(description_without_duplicate_list) 
        with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file: 
            writer = csv.writer(file) 
            for row in csv_rows: 
                writer.writerow(row)
```
But I'm not sure if this change is in line with the author's intention

**Comment by mhywithxy** [comment]
> [@LeeKoTo](https://github.com/LeeKoTo) 问题已解决。BeautfulSoup 解析网页时出错，导致 description 和 field name description 文件夹中的 CSV 文件为空。 首先，将以下代码添加到 Wireshark_field_crawler.py 文件中。
> 
> ```
> import re  
> pattern = r'<td>(.*?)</td>
> ```
> 
> 然后修改 field_crawler()
> 
> ```
> def field_crawler(protocol_names_list, field_name_description_csv_dir, description_csv_dir): 
>     for protocol_name in protocol_names_list: 
>         url = 'https://www.wireshark.org/docs/dfref/' + str(protocol_name[0]) + '/' + str(protocol_name) + '.html' 
>         print(url) 
>         response = requests.get(url) 
>         html_content = response.content 
>         soup = BeautifulSoup(html_content, 'html.parser') 
>         table = soup.find('table') 
>         field_name_list = [] 
>         description_list = [] 
>         for row in table.findAll('tr'): 
>             columns = row.findAll('td') 
>             if columns: 
>                 cleaned_content = re.sub(r'<wbr/>', '', str(columns[0])) 
>                 field_name = re.search(pattern, cleaned_content, re.DOTALL) 
>                 description = re.search(pattern, str(columns[1]), re.DOTALL) 
>                 field_name_list.append(field_name.group(1)) 
>                 description_list.append(description.group(1)) 
>         csv_file_name = str(protocol_name) + '_field_name_description.csv' 
>         csv_rows = zip(field_name_list, description_list) 
>         with open(os.path.join(field_name_description_csv_dir, csv_file_name), 'w', newline='') as file: 
>             writer = csv.writer(file) 
>             for row in csv_rows: 
>                 writer.writerow(row) 
>         description_without_duplicate_list = list(OrderedDict.fromkeys(description_list)) # Remove duplicate descriptions 
>         csv_file_name = str(protocol_name) + '_description.csv' 
>         csv_rows = zip(description_without_duplicate_list) 
>         with open(os.path.join(description_csv_dir, csv_file_name), 'w', newline='') as file: 
>             writer = csv.writer(file) 
>             for row in csv_rows: 
>                 writer.writerow(row)
> ```
> 
> 但我不太确定这种改动是否符合作者的本意。

您好我想请问一下该代码是否只需要按照自述文件加上您的改动去操作便可运行，还是说wrieshark字段抓取的工作也需要我们自己做呢，还是工程自动运行
